#ifndef DEFINEDEBUGGERHEADERGUARD
#define DEFINEDEBUGGERHEADERGUARD

#define SHOWINFO
#define SHOWWARNING

#ifdef SHOWWARNING
	#define SHADERWARNINGS

	#define INDEXBUFFERWARNING
	#define VBLAYOUTWARNING
#endif


#ifdef SHOWINFO
	#define SHADERDEBUG

	#define SHOWGLVERSION
	#define SHOWMSAA
	#define SHOWINITINFO
#endif

#endif